spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123456
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
      # 指定nacos server的地址
        server-addr: localhost:8848
        # 只能配置id不能配置名字，指定命名空间
        #namespace: 8a910f18-cff1-4fe0-91d7-86872572907b
        # 指定集群
        #cluster-name: NJ
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center

server:
  port: 8012