spring:
  datasource:
    url: jdbc:mysql://rm-bp19pa1b860r8hbhj4o.mysql.rds.aliyuncs.com:3306/user-center
    hikari:
      username: blog
      password: weiwei91
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
      # 指定nacos server的地址
        server-addr: 121.40.103.70:8848
        # 只能配置id不能配置名字，指定命名空间
        #namespace: 8a910f18-cff1-4fe0-91d7-86872572907b
        # 指定集群
        #cluster-name: NJ
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center

server:
  port: 8013

#rocketmq:
#  name-server: 127.0.0.1:9876